"""add pinned_release_mbid

Revision ID: 1a21eded4b7d
Revises: 40ef71b11eac
Create Date: 2026-04-23 23:29:36.409682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a21eded4b7d'
down_revision = '40ef71b11eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_release_mbid', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('pinned_release_mbid')

    # ### end Alembic commands ###
