"""add discogs_id to album, source to credit

Revision ID: 242b74fe0c9c
Revises: c4b46e3dabd7
Create Date: 2026-03-24 22:53:05.396371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242b74fe0c9c'
down_revision = 'c4b46e3dabd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discogs_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_album_discogs_id'), ['discogs_id'], unique=True)

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_credit_source'), ['source'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_source'))
        batch_op.drop_column('source')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_discogs_id'))
        batch_op.drop_column('discogs_id')

    # ### end Alembic commands ###
