"""backlog and review likes and comments

Revision ID: 25835994b04d
Revises: 8a792f7a63be
Create Date: 2026-04-09 03:37:37.681212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25835994b04d'
down_revision = '8a792f7a63be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'album_id')
    )
    with op.batch_alter_table('backlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backlog_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backlog_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backlog_user_id'))
        batch_op.drop_index(batch_op.f('ix_backlog_album_id'))

    op.drop_table('backlog')
    # ### end Alembic commands ###
