"""add color_accent

Revision ID: 2878af694988
Revises: cbec8aa55a12
Create Date: 2026-03-29 00:00:12.463114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2878af694988'
down_revision = 'cbec8aa55a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_accent', sa.String(length=7), nullable=True))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_accent', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('color_accent')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('color_accent')

    # ### end Alembic commands ###
