"""release_date and release_group_mbid

Revision ID: 38eca600d851
Revises: 2878af694988
Create Date: 2026-04-02 21:24:25.342661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38eca600d851'
down_revision = '2878af694988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_group_mbid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_album_release_group_mbid'), ['release_group_mbid'], unique=False)
        batch_op.drop_column('release_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_album_release_group_mbid'))
        batch_op.drop_column('release_date')
        batch_op.drop_column('release_group_mbid')

    # ### end Alembic commands ###
