"""follow system and backlog

Revision ID: 39095cb91158
Revises: 25835994b04d
Create Date: 2026-04-14 19:05:24.680704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39095cb91158'
down_revision = '25835994b04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_following_id'), ['following_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_following_id'))
        batch_op.drop_index(batch_op.f('ix_follow_follower_id'))

    op.drop_table('follow')
    # ### end Alembic commands ###
