"""add list and list_item models

Revision ID: 8223dfa31929
Revises: 39095cb91158
Create Date: 2026-04-16 22:08:57.321888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8223dfa31929'
down_revision = '39095cb91158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_user_id'), ['user_id'], unique=False)

    op.create_table('list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'album_id')
    )
    with op.batch_alter_table('list_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_item_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_item_list_id'), ['list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_item_list_id'))
        batch_op.drop_index(batch_op.f('ix_list_item_album_id'))

    op.drop_table('list_item')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_user_id'))

    op.drop_table('list')
    # ### end Alembic commands ###
