"""review likes and comments

Revision ID: 8a792f7a63be
Revises: 38eca600d851
Create Date: 2026-04-06 20:50:03.107988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a792f7a63be'
down_revision = '38eca600d851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_comment_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_comment_user_id'), ['user_id'], unique=False)

    op.create_table('review_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_id')
    )
    with op.batch_alter_table('review_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_like_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_like_user_id'), ['user_id'], unique=False)

    op.create_table('comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['review_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id')
    )
    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_like_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_like_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_like_comment_id'))

    op.drop_table('comment_like')
    with op.batch_alter_table('review_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_like_review_id'))

    op.drop_table('review_like')
    with op.batch_alter_table('review_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_comment_review_id'))

    op.drop_table('review_comment')
    # ### end Alembic commands ###
