"""added some relationships

Revision ID: b18aedd0dde3
Revises: b31d0e94b134
Create Date: 2026-02-12 22:58:08.568216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18aedd0dde3'
down_revision = 'b31d0e94b134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('mbid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('album_artist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('album_artist_album_id_artist_id_key'), type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_album_id'), ['album_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_album_id'))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('album_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('album_artist_album_id_artist_id_key'), ['album_id', 'artist_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('mbid',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
