"""add unique and index constraints

Revision ID: b31d0e94b134
Revises: ee3f6194b62c
Create Date: 2026-02-12 20:45:50.743764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31d0e94b134'
down_revision = 'ee3f6194b62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('album_mbid_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_album_mbid'), ['mbid'], unique=True)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('artist_mbid_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_artist_mbid'), ['mbid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_mbid'))
        batch_op.create_unique_constraint(batch_op.f('artist_mbid_key'), ['mbid'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('country',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_mbid'))
        batch_op.create_unique_constraint(batch_op.f('album_mbid_key'), ['mbid'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('release_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
