"""empty message

Revision ID: c4b46e3dabd7
Revises: 5604057969a6
Create Date: 2026-03-12 17:12:23.236460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b46e3dabd7'
down_revision = '5604057969a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'artist_name', 'role', name='uq_credit_track_artist_role')
    )
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_track_id'))
        batch_op.drop_index(batch_op.f('ix_credit_artist_id'))

    op.drop_table('credit')
    # ### end Alembic commands ###
