"""track mbid unique per album

Revision ID: d0bf05f1e8c3
Revises: 1a21eded4b7d
Create Date: 2026-04-23 23:41:21.247047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bf05f1e8c3'
down_revision = '1a21eded4b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_mbid'))
        batch_op.create_index(batch_op.f('ix_track_mbid'), ['mbid'], unique=False)
        batch_op.create_unique_constraint('uq_track_album_mbid', ['album_id', 'mbid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_constraint('uq_track_album_mbid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_track_mbid'))
        batch_op.create_index(batch_op.f('ix_track_mbid'), ['mbid'], unique=True)

    # ### end Alembic commands ###
