"""add discogs_id to album, source to credit

Revision ID: fbcbb603a747
Revises: 242b74fe0c9c
Create Date: 2026-03-25 04:30:04.671544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcbb603a747'
down_revision = '242b74fe0c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_credit_source'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_source'), ['source'], unique=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
